### ISSUE TITLE
Error: A sibling of this resource already has a variable path part -- only one is allowed

### ISSUE THREAD

**Issue by azappa** [dawson-org/dawson-cli#175] opened 2017-04-13 08:10 UTC
ref: https://github.com/dawson-org/dawson-cli/issues/166

I write a lambda file with two get routes (they share the same code, i mede a second one to show an alternative preview)

```javascript
export async function service (event) {
  const _lang = event.params.path.lang;
  const _uid = event.params.path.serviceUid;

  console.log(`service page called with uid ${_uid} and lang ${_lang}.`);
  
  <… my code>
}
service.api = {
  path: '{lang}/service/{serviceUid}'
};

export async function serviceAlt (event) {
  const _lang = event.params.path.lang;
  const _uid = event.params.path.uidForService;

  console.log(`service page called with uid ${_uid} and lang ${_lang}.`);
  
  <… my code>
}
serviceAlt.api = {
  path: '{lang}/serviceAlt/{uidForService}'
};
```

The error I get:

```bash
   ┌──────────────┬───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────┐
   │ Timestamp    │ Status        │ Reason                                                                                            │ Logical Id            │
   ├──────────────┼───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────┤
   │ un minuto fa │ UPDATE_FAILED │ Resource update cancelled                                                                         │ LambdaEvents          │
   ├──────────────┼───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────┤
   │ un minuto fa │ CREATE_FAILED │ A sibling ({serviceUid}) of this resource already has a variable path part -- only one is allowed │ ResourceUidForService │
   └──────────────┴───────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────┘
```

**Comment by lusentis** [comment] 2017-06-25 21:32
Can't reproduce this issue with the latest release (v0.28), I'm closing for now, feel free to re-open with further details and a link to a project/report/gist that shows this error.

**Closed by lusentis** 2017-06-25 21:32 UTC
Labels: wontfix
